### PR TITLE
Update package.json

### PR DESCRIPTION
**Pull request by realsoelynn**
I updated this so that it can easily pick up the patch from dependency easily.

### CODE REVIEW

**Comment by realsoelynn** [comment]
@daniel-lundin please merge this and help us republish both packages :D

Thank you so much

**Comment by daniel-lundin** [comment]
Sure!

**Comment by daniel-lundin** [comment]
@soelynn Just published 0.0.8 on npm, let me know how it works out!

**Comment by realsoelynn** [comment]
@daniel-lundin it worked. Thank you so much :)

**Comment by realsoelynn** [comment]
Awesome library to use!!!

**Pull request merged**
