### PR TITLE
Add colors to ConfettiConfig typings

### PR DESCRIPTION
**Pull request by danysirota**

### CODE REVIEW

**Comment by panmona** [comment]
Shouldn't the colors be optional?

**Comment by danysirota** [comment]
Yup. Done.

**Comment by panmona** [comment]
Looks good to me. 

@daniel-lundin

**Comment by daniel-lundin** [comment]
Will release later today

**Comment by danysirota** [comment]
Thanks

**Comment by daniel-lundin** [comment]
Just released 0.0.10

**Pull request merged**
