### PR TITLE
Add typings to Confetti component

### PR DESCRIPTION
**Pull request by panmona**
I use this module in a typescript project and there weren't any typings for Typescript so I added them for others to use.
@daniel-lundin

### CODE REVIEW

**Comment by daniel-lundin** [comment]
Nice! I don't use TypeScript myself, but don't you need to reference them from package.json somehow or is it enough that the declaration has the same name as the js file?

**Comment by panmona** [comment]
As far as I know there are two ways: 
1. put `index.d.ts` into the root (I choose that approach here)
2. put a `types` declaration in the `package.json`

**Comment by daniel-lundin** [comment]
Ok, cool, will do a new release soon!

**Comment by daniel-lundin** [comment]
published as 0.0.9

**Comment by panmona** [comment]
@daniel-lundin Thanks a lot. Works perfectly 🎉 <- this is confetti 😉

**Pull request merged**
